name: Secret Scanning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          exit-code: 1

  trufflehog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan with TruffleHog
        uses: docker://trufflesecurity/trufflehog
        with:
          args: github --repo https://github.com/${{ github.repository }}
